siteName: Mind the mind now!
productionUrl: https://www.mindthemind-now.org/
languages:
  - code: fr
    name: Fran√ßais
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
collections:
  - people
